documentation
multipleCircuits
	"Per http://maymay.net/blog/2013/02/20/howto-use-tor-for-all-network-traffic-by-default-on-mac-os-x/"
	
	"If you’d like to be even harder to track, you can take the time to have Tor listen for connection requests on multiple different ports. Although you don’t have to do this, it’s a good idea because it means you can send network traffic along different routes (called “circuits”) inside the Tor network itself. This way, you might appear to be browsing the Web from France but checking your email from Canada at the same time, and an attacker would need to be watching both locations to have a shot at figuring out that both the Web and email traffic were coming from you. "