"
# Installation
On Mac, it seems ([per SO](https://stackoverflow.com/a/39814799)) that ""the way"" is via direct download using [this link](https://www.pdflabs.com/tools/pdftk-the-pdf-toolkit/pdftk_server-2.02-mac_osx-10.11-setup.pkg). The [link](https://www.pdflabs.com/tools/pdftk-server/) on the website has been out-of-date from 2016 and is still so as of 9/13/2020. There used to be a Homebrew formula, but it was removed due to permissions issues; there are several Homebrew GH issues about this; google if interested.


"
Class {
	#name : 'CwPDFtk',
	#superclass : 'Object',
	#category : 'ComputerWorld-Apps'
}
