"
# Section Markers
See instructions [here](https://mikemurphyco.medium.com/322-youtube-how-to-add-chapter-markers-be4df2473885)
"
Class {
	#name : 'CwYouTube',
	#superclass : 'Object',
	#category : 'ComputerWorld-Apps',
	#package : 'ComputerWorld',
	#tag : 'Apps'
}

{ #category : 'as yet unclassified' }
CwYouTube class >> keyboardShortcuts [
	"https://sites.google.com/a/umich.edu/going-google/accessibility/google-keyboard-shortcuts---youtube
	
	Playback Speed: < and >
	Skip: 1 - 9"
]
